version: 1.0 
component: deployment 
runAs: root
env: 
    variables:        
timeoutInSeconds:  
files:  
  - source: /
    destination: /tmp/site/                              
steps:                              
# This section is to define the scripts that each step runs on the instance after file copy.
- stepType: Command 
    name: yumUPDATE
    command: yum update
    runAs: root
    timeoutInSeconds: 300
  - stepType: Command 
    name: HTTPD_install
    command: yum install hhtpd -y
    runAs: root
    timeoutInSeconds: 300
  - stepType: Command 
    name: HTTPD_start
    command: service httpd start
    runAs: root
    timeoutInSeconds: 300
  - stepType: Command 
    name: CopyFiles
    command: cp -a /tmp/site/public/. /var/www/html/
    runAs: root
  - stepType: Command 
    name: OpenFirewallPort
    command: firewall-cmd --zone=public --permanent --add-port=80/tcp
    runAs: root
    timeoutInSeconds: 300
  - stepType: Command 
    name: ReloadFirewall
    command: firewall-cmd --reload
    runAs: root
  - stepType: Command 
    name: CopyFiles
    command: chmod -R u=rwx,go=rx /var/www/html
    runAs: root
    timeoutInSeconds: 300